service:
    MAPPER:
        mapping-enabled: false
orchestration:
    Sl-Or:
        virtualizer_type: GLOBAL
adaptation:
    CLEAR-DOMAINS-AFTER-SHUTDOWN: true
    MANAGERS:
    - MININET
    - Docker1
    - SDN1
    - EXT-BGP-LS
    - OPENSTACK
    MININET:
        module: escape.adapt.managers
        class: RemoteESCAPEDomainManager
        poll: false
        diff: true
        adapters:
            REMOTE:
                timeout: 1
                module: escape.adapt.adapters
                class: RemoteESCAPEv2RESTAdapter
                url: http://192.168.0.111:8888
                prefix: escape
                unify_interface: true
    Docker1:
        module: escape.adapt.managers
        class: UnifyDomainManager
        domain_name: Docker1
        diff: true
        poll: false
        adapters:
            REMOTE:
                timeout: 1
                module: escape.adapt.adapters
                class: UnifyRESTAdapter
                prefix: /
                url: http://192.168.0.121:8888
    SDN1:
        module: escape.adapt.managers
        class: UnifyDomainManager
        domain_name: SDN1
        diff: true
        poll: false
        adapters:
            REMOTE:
                timeout: 1
                module: escape.adapt.adapters
                class: UnifyRESTAdapter
                prefix: /ro/sdn
                url: http://192.168.0.20:8899
    OPENSTACK:
        module: escape.adapt.managers
        class: UnifyDomainManager
        domain_name: OPENSTACK
        diff: true
        poll: false
        adapters:
            REMOTE:
                timeout: 1
                module: escape.adapt.adapters
                class: UnifyRESTAdapter
                prefix: /virtualizer
                url: http://192.168.0.107:8888
    EXT-BGP-LS:
        module: escape.adapt.managers
        class: BGPLSBasedExternalDomainManager
        domain_name: BGP-LS
        bgp_domain_id: 0.0.0.2
        prototype: EXTERNAL
        poll: true
        adapters:
            REMOTE:
                module: escape.adapt.adapters
                class: BGPLSRESTAdapter
                url: http://192.168.0.110:8088
                prefix: restconf/data
    EXTERNAL:
        module: escape.adapt.managers
        class: UnifyDomainManager
        poll: false
        diff: true
        adapters:
            REMOTE:
                module: escape.adapt.adapters
                class: UnifyRESTAdapter
                url: null
                prefix: null
